### ISSUE TITLE
EDA sampling generates solutions out of bounds

### ISSUE THREAD

**Issue by rgmantovani** [yasserglez/copulaedas#1]
Hi, 

i'm using copulaedas with 'mlr' package to tune SVMs hyper-parameters. Even specifying the upper and lower bounds, the eda model is generating/sampling new solutions out of bounds. Is there any way to access edaSample to correct it or force an individual to be in the hyper-space restrictions ?

![screen shot 2015-11-03 at 6 12 05 pm](https://cloud.githubusercontent.com/assets/5933552/10915304/6ff13b9e-8256-11e5-8cc4-a1f6b07e8160.png)

I'm using copulaedas_1.4.2 version.

**Comment by yasserglez** [comment]
Hi Rafael,

That's the intented behavior if you're using normal marginal distributions (the default) -- since the normal distribution is unbounded. You can use truncated normal marginal distributions if you always need samples within the variable bounds. 

I don't see the definition of `makeTuneControlEDA` in the screenshot you posted, but it probably uses something like this to create the `EDA` instance for the UMDA: `CEDA(copula = "indep", margin = "norm")`. Try changing `margin = "norm"` by `margin = "truncnorm"`. 

Please, let me know if that fixes the problem.

**Comment by rgmantovani** [comment]
Hi Yasser,

That function is just a wrapper and does something like that:

![screen shot 2015-11-03 at 7 11 15 pm](https://cloud.githubusercontent.com/assets/5933552/10916983/afcab58a-825e-11e5-9673-95438de5588d.png)

I changed, as you suggested and worked. Thank you.
